#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from sqlalchemy import Column, Float, ForeignKey, String, TIMESTAMP, Text, text
from sqlalchemy.dialects.mysql import CHAR, BIGINT, INTEGER, LONGTEXT, MEDIUMINT, SMALLINT, TINYINT
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class SpawnsCreatures(Base):
    __tablename__ = 'spawns_creatures'

    spawn_id = Column(INTEGER(10), primary_key=True, comment=u'Global Unique Identifier')
    spawn_entry1 = Column(ForeignKey(u'creature_template.entry', ondelete=u'CASCADE', onupdate=u'CASCADE'), nullable=False, index=True, server_default=text("'0'"), comment=u'Creature Template Id')
    spawn_entry2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"), comment=u'Creature Template Id')
    spawn_entry3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"), comment=u'Creature Template Id')
    spawn_entry4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"), comment=u'Creature Template Id')
    map = Column(SMALLINT(5), nullable=False, index=True, server_default=text("'0'"), comment=u'Map Identifier')
    display_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    equipment_id = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    position_x = Column(Float, nullable=False, server_default=text("'0'"))
    position_y = Column(Float, nullable=False, server_default=text("'0'"))
    position_z = Column(Float, nullable=False, server_default=text("'0'"))
    orientation = Column(Float, nullable=False, server_default=text("'0'"))
    spawntimesecsmin = Column(INTEGER(10), nullable=False, server_default=text("'120'"))
    spawntimesecsmax = Column(INTEGER(10), nullable=False, server_default=text("'120'"))
    wander_distance = Column(Float, nullable=False, server_default=text("'5'"))
    health_percent = Column(Float, nullable=False, server_default=text("'100'"))
    mana_percent = Column(Float, nullable=False, server_default=text("'100'"))
    movement_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spawn_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    visibility_mod = Column(Float, server_default=text("'0'"))
    ignored = Column(TINYINT(1), nullable=False, server_default=text("'0'"))


class Worldports(Base):
    __tablename__ = 'worldports'

    entry = Column(INTEGER(11), autoincrement=True, primary_key=True)
    x = Column(Float, nullable=False, server_default=text("'0'"))
    y = Column(Float, nullable=False, server_default=text("'0'"))
    z = Column(Float, nullable=False, server_default=text("'0'"))
    o = Column(Float, nullable=False, server_default=text("'0'"))
    map = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    name = Column(String(255), nullable=False, server_default=text("''"))


class SpawnsGameobjects(Base):
    __tablename__ = 'spawns_gameobjects'

    spawn_id = Column(INTEGER(10), primary_key=True, comment='Global Unique Identifier')
    spawn_entry = Column(ForeignKey('gameobject_template.entry', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, index=True, server_default=text("'0'"), comment='Gameobject Identifier')
    spawn_map = Column(SMALLINT(5), nullable=False, index=True, server_default=text("'0'"), comment='Map Identifier')
    spawn_positionX = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_positionY = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_positionZ = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_orientation = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_rotation0 = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_rotation1 = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_rotation2 = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_rotation3 = Column(Float, nullable=False, server_default=text("'0'"))
    spawn_spawntimemin = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    spawn_spawntimemax = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    spawn_animprogress = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spawn_state = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spawn_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    spawn_visibility_mod = Column(Float, nullable=True, server_default=text("'0'"))
    ignored = Column(TINYINT(1), nullable=False, server_default=text("'0'"))


class CreatureTemplate(Base):
    __tablename__ = 'creature_template'

    entry = Column(MEDIUMINT(8), primary_key=True, server_default=text("'0'"))
    display_id1 = Column(MEDIUMINT(8), nullable=False, index=True, server_default=text("'0'"))
    display_id2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    display_id3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    display_id4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    name = Column(CHAR(100), nullable=False, index=True, server_default=text("'0'"))
    subname = Column(CHAR(100))
    gossip_menu_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    level_min = Column(TINYINT(3), nullable=False, server_default=text("'1'"))
    level_max = Column(TINYINT(3), nullable=False, server_default=text("'1'"))
    health_min = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    health_max = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    mana_min = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    mana_max = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    armor = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    faction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    npc_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    speed_walk = Column(Float, nullable=False, server_default=text("'1'"), comment='Result of 2.5/2.5, most common value')
    speed_run = Column(Float, nullable=False, server_default=text("'1.14286'"), comment='Result of 8.0/7.0, most common value')
    scale = Column(Float, nullable=False, server_default=text("'1'"))
    detection_range = Column(Float, nullable=False, server_default=text("'20'"))
    call_for_help_range = Column(Float, nullable=False, server_default=text("'5'"))
    leash_range = Column(Float, nullable=False, server_default=text("'0'"))
    rank = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    xp_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    dmg_min = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_school = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    attack_power = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    dmg_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    base_attack_time = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    ranged_attack_time = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    unit_class = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    unit_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    dynamic_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    beast_family = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    trainer_type = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    trainer_spell = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    trainer_class = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    trainer_race = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    ranged_dmg_min = Column(Float, nullable=False, server_default=text("'0'"))
    ranged_dmg_max = Column(Float, nullable=False, server_default=text("'0'"))
    ranged_attack_power = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    type_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    pickpocket_loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    skinning_loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    holy_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    fire_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    nature_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    frost_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    shadow_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    arcane_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spell_id1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_list_id = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    pet_spell_list_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    gold_min = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    gold_max = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ai_name = Column(CHAR(64), nullable=False, server_default=text("''"))
    movement_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    inhabit_type = Column(TINYINT(3), nullable=False, server_default=text("'3'"))
    civilian = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    racial_leader = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    regeneration = Column(TINYINT(3), nullable=False, server_default=text("'3'"))
    equipment_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    trainer_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    vendor_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    mechanic_immune_mask = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    school_immune_mask = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    flags_extra = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    script_name = Column(CHAR(64), nullable=False, server_default=text("''"))
